flatpak install flathub ch.threema.threema-web-desktop -y
flatpak install flathub com.bitwarden.desktop -y
flatpak install flathub com.discordapp.Discord -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub com.github.xournalpp.xournalpp -y
flatpak install flathub com.heroicgameslauncher.hgl -y
flatpak install flathub com.hunterwittenborn.Celeste -y
flatpak install flathub com.mattjakeman.ExtensionManager -y
flatpak install flathub com.rtosta.zapzap -y
flatpak install flathub com.slack.Slack -y
flatpak install flathub com.spotify.Client -y
flatpak install flathub com.valvesoftware.Steam -y
flatpak install flathub com.vysp3r.ProtonPlus -y
flatpak install flathub im.riot.Riot -y
flatpak install flathub io.freetubeapp.FreeTube -y
flatpak install flathub io.github.brunofin.Cohesion -y
flatpak install fedora org.fedoraproject.MediaWriter -y
flatpak install fedora org.gnome.Calculator -y
flatpak install fedora org.gnome.Calendar -y
flatpak install fedora org.gnome.Characters -y
flatpak install fedora org.gnome.Cheese -y
flatpak install fedora org.gnome.Connections -y
flatpak install fedora org.gnome.Contacts -y
flatpak install fedora org.gnome.Evince -y
flatpak install fedora org.gnome.Extensions -y
flatpak install fedora org.gnome.Logs -y
flatpak install fedora org.gnome.Loupe -y
flatpak install fedora org.gnome.Maps -y
flatpak install fedora org.gnome.NautilusPreviewer -y
flatpak install fedora org.gnome.TextEditor -y
flatpak install fedora org.gnome.Weather -y
flatpak install fedora org.gnome.baobab -y
flatpak install fedora org.gnome.clocks -y
flatpak install fedora org.gnome.font-viewer -y
flatpak install flathub org.gnucash.GnuCash -y
flatpak install flathub org.keepassxc.KeePassXC -y
flatpak install flathub org.libreoffice.LibreOffice -y
flatpak install flathub org.mozilla.Thunderbird -y
flatpak install flathub org.mozilla.firefox -y
flatpak install flathub org.signal.Signal -y
flatpak install flathub org.telegram.desktop -y
flatpak install flathub org.videolan.VLC -y
flatpak install flathub us.zoom.Zoom -y
